### ISSUE TITLE
Update to 1.4 API

### ISSUE THREAD

**Issue by dwhitena** [kalugny/pypachy#2]
Pachyderm version 1.4 is being release tomorrow officially.  We will need to update the client to the 1.4 API as there are a few differences.  We would be happy to discuss the changes on Slack or here, and happy to help where we are able.  Thanks!

**Comment by kalugny** [comment]
I see that what's changed in the protobuf spec are methods related to "Objects".
Can you elaborate what this is about? I can't seem to have access to the new documentation.

**Comment by dwhitena** [comment]
@kalugny the new documentation is up now: http://docs.pachyderm.io/en/latest/.  I'm not sure about the `Objects`, our pipeline spec etc has changed in this recent release.  Some of the high level info is here: https://medium.com/pachyderm-data/pachyderm-1-4-performance-boosts-simplified-data-partitioning-deployment-flexibility-and-more-c483e4942a6d.

To get in the details, it's probably best to discuss this on Pachyderm slack so that other can weigh in.  However, maybe you can find what you need with the new docs.  Thanks again!  Just let us know how we can help.
