### ISSUE TITLE
delete_all() raises an exception

### ISSUE THREAD

**Issue by thedrow** [kalugny/pypachy#6]
```
    def delete_all(self):
>       self.stub.DeleteAll()
E       TypeError: __call__() missing 1 required positional argument: 'request'
```
I'm not sure what request is unfortunately.

**Comment by kalugny** [comment]
Hi!
I've updated pypachy.
Can you check if this issue is fixed?

**Comment by thedrow** [comment]
Will do :)

**Comment by kalugny** [comment]
It seems it's still present. I'm not yet sure how to solve it. There's a required `request` parameter but no request that is suitable. The Go client doesn't have that.
I'll try to debug this further.
